### PR TITLE
Add support for OPENID_CONNECT

### PR DESCRIPTION
**Pull request by snapstrat-devops**
This code, while it looks correct, does not appear to work due to a problem with AppSync/Cloudformation.

See this: https://forums.aws.amazon.com/thread.jspa?threadID=283342

### CODE REVIEW

**Comment by francisu** [comment]
This is now ready to go (I made the correction as suggested in the AWS forums thread link in the initial comment); I have verified that it creates the API and correctly populates all of the fields possible in the OpenIDConnectConfig.

Can you merge this please?

**Comment by sid88in** [comment]
@francisu you might have to resolve conflicts one last time and I'll merge it. Looks good

**Comment by francisu** [comment]
Thanks so much! You should be all set now.

**Comment by francisu** [comment]
Do you know when you will do an npm publish on this?

**Pull request merged**
