### PR TITLE
Support `functionAlias` in lambda data sources.

### LINKED ISSUE #365: Lambda functionName does not pick up alias
By providing `provisionedConcurrency` or `reservedConcurrency` to the function itself, serverless will create an alias for the lambda. But this plugin does not automatically pick up the generated alias/qualifiers and only connects to the $LATEST version without scaling/throttling.

Is it supposed to be able to pick it up, or is there any other ways to do it?

### PR DESCRIPTION
**Pull request by vicary**
Resolves #365

### CODE REVIEW

**Review by bboure — APPROVED** [review]
Thanks! @vicary  LGTM

**Comment by bboure** [comment]
@vicary please fix the lining, and this is good to go.
Bonus point for adding tests.

**Comment by vicary** [comment]
first time doing snapshot tests, feels quite usable tbh.

**Comment by bboure** [comment]
Thanks again @vicary

**Pull request merged**
