### PR TITLE
Sync config

### PR DESCRIPTION
**Pull request by bboure**
Folow up of https://github.com/sid88in/serverless-appsync-plugin/pull/363

### CODE REVIEW

**Comment by bboure** [comment]
@hounded thanks for your time on this. 
Please review this, and if you can, have it a try to make sure it works.

**Comment by hounded** [comment]
happy to test 
noob question 
npm install git://github.com/hounded/serverless-appsync-plugin.git#syncConfig --save
does not seem to install syncConfig

**Comment by hounded** [comment]
image
image
I checked the serverless appsync src in the node modules defen running the syncConfig branch, but it doesn't look like it is running

**Comment by hounded** [comment]
image

got the table enabled

**Comment by bboure** [comment]
Thanks for taking the time to test this @hounded 
I found a couple of issues that I fixed. 

You should now be able to test the `syncConfig` feature, just by setting the `sync` config in your `mappingTemplates`

**Comment by hounded** [comment]
image
image

can confirm success nice work

**Comment by bboure** [comment]
Awesome, I will merge this.

Thanks again for your help

**Pull request merged**
