### PR TITLE
Add AWS scalar types before validating the schema

### LINKED ISSUE #118: Add support for new AppSync types for when validating the schema
Announcement: https://aws.amazon.com/about-aws/whats-new/2018/07/aws-appsync-releases-enhanced-capabilities-nocode-graphql/

New types:

- AWSDate
- AWSTime
- AWSDateTime
- AWSTimestamp
- AWSEmail
- AWSJSON
- AWSURL
- AWSPhone
- AWSIPAddress

Current error:

```
  Type "AWSURL" not found in document.
```

### PR DESCRIPTION
**Pull request by patrick91**
Closes #118 

I'm appending the types at the end of the schema, seems easier than adding the type in the AST object :)

### CODE REVIEW

**Comment by Skaronator** [comment]
Could we get this merged? @sid88in

**Comment by sid88in** [comment]
🎉

**Comment by jsleeuw** [comment]
Any idea when this will be released?

**Comment by Throttlebyte** [comment]
@jsleeuw  this isn't as ideal as a release, but I found development is happening so fast on this plugin I can't wait for npm versions.  So I refer to it in my package.json as:

`
"devDependencies": {
    "serverless-appsync-plugin": "github:sid88in/serverless-appsync-plugin",
}
`

**Comment by jsleeuw** [comment]
Thanks @Throttlebyte, I'll give that a whirl

**Pull request merged**
