### PR TITLE
Implement Caching

### LINKED ISSUE #276: Appsync Resolver Caching
Appsync now has built in caching capability, at a full api level, and more interesting, at a resolver level. Curious if anyone is working on getting this working within this plugin? I think adding the ability to annotate that a resolver should cached and a TTL (60-3600 seconds) is supported.

Reference:
https://aws.amazon.com/blogs/mobile/appsync-caching-transactions/

### PR DESCRIPTION
**Pull request by bboure**
Resolves #276

### CODE REVIEW

**Comment by bboure** [comment]
@michaelrhoden Want to help testing this?

**Comment by rakeshmenon** [comment]
@bboure - Is this tested or do you need any help?

I've created a PR to your branch (feature/caching) to fix the failing snapshots.

**Comment by bboure** [comment]
@rakeshmenon  I haven't tested this (yet).
Any help is appreciated :)

**Comment by rakeshmenon** [comment]
@bboure I was not able to get it to work.

I tried using it by changing the package version to:
**`sid88in/serverless-appsync-plugin#feature/caching`**

I added the caching confirguration in serverless.yml as follows -

**Under appSync**:
```
  caching:
      ttl: 60
      behavior: PER_RESOLVER_CACHING
      type: 'T2_SMALL'
```

**Under each mapping template**:
```
  caching:
      ttl: 30
```

It was an **update stack** operation - as the AppSync endpoint already exists. The update stack operation went through - but did not enable the caching options in the resolvers or change the global caching config.

**Comment by bboure** [comment]
THank you @rakeshmenon  for testing this.
Can you confirm that the plugin got updated correctly in your `node_modules` folder?

instead of changing your package.json, you can also try to use [npm link](https://docs.npmjs.com/cli/link.html) or  [yarn link](https://yarnpkg.com/lang/en/docs/cli/link/)

**Comment by rakeshmenon** [comment]
Yes - the plugin was updated in the node_modules directory.

Screenshot 2019-12-17 22 05 31

**Comment by bboure** [comment]
Fixed some issues and this is *almost* working as expected. 
I came across an issue when disabling cache on a resolver. It seems related to CloudFormation.
I [opened an issue here](https://github.com/aws/aws-appsync-community/issues/76)

**Comment by rakeshmenon** [comment]
w00t! I'll test this out today. Hopefully the Cloudformation issue gets addressed soon :)

**Comment by rakeshmenon** [comment]
Have tested this PR - I faced the same issue. Caching at the resolver level is not clearing when I removed caching config.

Everything else works fine!

**Comment by bboure** [comment]
Cfn bug has been confirmed by AWS. After testing this on `us-east-2` where the bug  has been fixed. All seems to be working s expected. 
Will merge this soon

**Comment by rakeshmenon** [comment]
Hi @bboure - when will the new version of the plugin be published with this change included?

**Comment by bboure** [comment]
@rakeshmenon the plan is to release soon. 
I just want to make sure that there are no breaking changes

**Comment by bboure** [comment]
@rakeshmenon This is now part of the v1.2.0 release. Enjoy!

**Pull request merged**
