### PR TITLE
Delta sync config

### LINKED ISSUE #309: Support Versioned and DeltaSyncConfig
AppSync currently supports versioning on DynamoDB data sources.
https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html

I want to configure this options.

Example of CloudFormation template is below.
we need `Versioned` and `DeltaSyncConfig` sections.

```yaml
  DynamoDBPostsTableDatasource:
    Type: AWS::AppSync::DataSource
    Properties:
      Type: AMAZON_DYNAMODB
      Name: posts
      ApiId:
        Fn::GetAtt:
        - DeltaSyncApi
        - ApiId
      ServiceRoleArn: !GetAtt AppSyncTutorialAmazonDynamoDBRole.Arn
      DynamoDBConfig:
        TableName:
          Ref: DynamoDBTableDeltaSyncPostsTable
        AwsRegion:
          Ref: AWS::Region
        UseCallerCredentials: FALSE
        Versioned: TRUE
        DeltaSyncConfig:
          DeltaSyncTableName:
            Ref: DynamoDBTableDeltaSyncDeltaTable
          DeltaSyncTableTTL: 60
          BaseTableTTL: 0
```

thanks.

### PR DESCRIPTION
**Pull request by bboure**
Replaces #313 
Fixes #309

### CODE REVIEW

**Comment by bboure** [comment]
@yyoshiki41  I took your branch and added some tests.

**Comment by yyoshiki41** [comment]
@bboure 
Thanks 👍

**Comment by bboure** [comment]
Thanks to you @yyoshiki41 
Merged. Will be in the next release.

**Comment by bboure** [comment]
Released in 1.3.0 🎉

**Pull request merged**
