### PR TITLE
Add opensearch datasource

### PR DESCRIPTION
**Pull request by nvanlo**

### CODE REVIEW

**Comment by nvanlo** [comment]
This pull request adds the OPEN SEARCH datasource as an alternative to the deprecated ELASTIC SEARCH

**Comment by bboure** [comment]
Thank you @nvanlo !
LGTM.
Could you add a couple of tests?

**Comment by nvanlo** [comment]
> Thank you @nvanlo ! LGTM. Could you add a couple of tests?

Done!

**Comment by bboure** [comment]
Done,

Thank you! and sorry for the mess with both PRs

**Pull request merged**
