### PR TITLE
Fix RESOURCE_API typo

### PR DESCRIPTION
**Pull request by ZY-Ang**
Should be GraphQlApi, not GraphQLApi

### CODE REVIEW

**Comment by sid88in** [comment]
@ZY-Ang is this a critical fix where we need to create a new version or can this wait without any blocker?

**Comment by bboure** [comment]
@sid88in I think this breaks backward compatibility. So it should be released asap
@ZY-Ang  ?

**Comment by ZY-Ang** [comment]
Yeah. My bad.

**Comment by sid88in** [comment]
ok doing another version. thanks guys

**Pull request merged**
