### PR TITLE
Export the stack outputs

### PR DESCRIPTION
**Pull request by dillonbrowne**
Referencing Issue #390, This allows cross-stack reference to be able to use `Fn::ImportValue` in other CF stacks.

### CODE REVIEW

**Comment by bboure** [comment]
Thank you for your contribution @dillonbrowne !!
LGTM. 

Could you please
- add/update unit tests
- document it in the README

Thanks!

**Comment by dillonbrowne** [comment]
@bboure README is updated. Currently jest is only unit testing the API key. There is no unit test for stack outputs other than the default keys.

**Comment by bboure** [comment]
Thanks!
Your branch got some conflicts after merging another PR (sorry).
Can you please fix it, and I'll merge it!

**Review by bboure — APPROVED** [review]
I resolved the conflict.

Thank you!

**Pull request merged**
