### PR TITLE
Add data sources

### PR DESCRIPTION
**Pull request by jpstrikesback**
This adds data sources from config. See #34 

ToDo:
- [x] DynamoDB data source (DS)
- [x] Elastic Search DS
- [x] Lambda DS
- [ ] tests

### CODE REVIEW

**Comment by jpstrikesback** [comment]
this needs tests :)

**Comment by sid88in** [comment]
thanks @jpstrikesback would be great if you could run 1 test E2E and we can then merge this

**Comment by jpstrikesback** [comment]
Sounds good, I also wanna push an elastic search source and lambda source in this PR.

Side note: if you know of any good examples of E2E tests with serverless, I’d love to copy someone 😀

**Comment by sid88in** [comment]
@jpstrikesback not sure how much we can test appsync itself (although we could try testing lambda function) but for now I would recommend manual E2E testing.

**Comment by sid88in** [comment]
thanks @jpstrikesback !!!

**Pull request merged**
