### PR TITLE
Add support for Open ID config

### PR DESCRIPTION
**Pull request by cc07**
Allow serverless to build template with OpenIDConfig

### CODE REVIEW

**Comment by sid88in** [comment]
@cc07 can you please add some test screenshots?

**Comment by francisu** [comment]
Here is an image of it working: https://ibb.co/kTO20y  Can you merge this?

**Comment by francisu** [comment]
And another: ﻿﻿https://ibb.co/hoikLy

**Comment by sid88in** [comment]
@francisu @cc07  we just restructured the repository. Can you please sync with master and remove conflicts and test again? 

thanks
Sid

**Comment by ajmath** [comment]
Replaced by #95

**Pull request closed without merging**
