### PR TITLE
fix: generate correct dynamodb IamStatement

### PR DESCRIPTION
**Pull request by ebisbe**
When defining 

```
dataSources:
    tableDataSource:
      type: AMAZON_DYNAMODB
      description: 'Main table events for everything. Events, users, guests.'
      config:
        tableName: !Ref Table
```

The generated IamRoleStatement is:

```
"Resource": [
                "arn:aws:dynamodb:eu-west-1:679049160385:table/[Object object]",
                "arn:aws:dynamodb:eu-west-1:679049160385:table/[Object object]/*"
            ],
```

This PR fixes that issue.

### CODE REVIEW

**Comment by bboure** [comment]
LGTM! Thanks for the first contrib to v2 🎉 

I changed the base branch to `alpha` which is the new main branch for v2. 

Please, would you mind fixing the existing tests, and adding a new one for the use case you fixed?

**Comment by ebisbe** [comment]
When I checked I didn't find related tests to the changes I was doing. If there are files testing that part mind you pointing me the direction? I'll gladly review everything.

Do I have to do anything related with  the change from `v2` to `alpha` ?

**Comment by ebisbe** [comment]
I have added a new test with the particular use case:

**Comment by bboure** [comment]
LGTM 🚀 

Thanks for the contrib!

**Pull request merged**
